sudo: required

services:
    - docker

cache:
    directories:
        - /home/travis/docker/
env:
    global:
        - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz

before_install:
    - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
    - docker version
    - docker-compose -f docker-compose.yml up -d

script:
    - docker-compose version
    - docker-compose -f docker-compose.yml run laravel php artisan dusk
    - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi