version: '2'
services:
    laravel:
        build:
            image: hanhan1978/docker-laravel54-skelton
            dockerfile_path: Dockerfile
        links:
          - mysql:mysql.local
        volumes:
          - ./laravel:/var/www/laravel
    nginx:
        image: nginx:1.11-alpine
        ports:
            - "80:80"
        links:
            - laravel:fpm.local
        volumes:
            - ./var/conf/default.conf:/etc/nginx/conf.d/default.conf
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=laravel
          - MYSQL_USER=developer
          - MYSQL_PASSWORD=developer
        volumes:
          - ./var/mysql:/var/lib/mysql
    selenium:
        image: selenium/standalone-chrome:latest

