version: '2'
services:
  laravel:
    build: .
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - app
  nginx:
    image: nginx:1.11-alpine
    ports:
        - "80:80"
    volumes:
        - ./var/conf/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
        - laravel
    networks:
      app:
        aliases:
          - nginx.local
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    volumes:
      - ./var/mysql:/var/lib/mysql
    networks:
      - app
  selenium:
    image: selenium/standalone-chrome:latest
    networks:
      app:
        aliases:
          - selenium.local
networks:
  app:
