version: '2'
services:
  laravel:
    build: .
  nginx:
    image: nginx:1.11-alpine
    ports:
        - "80:80"
    volumes:
        - ./var/conf/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
        - laravel
    links:
      - laravel:laravel
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    volumes:
      - ./var/mysql:/var/lib/mysql
  selenium:
    image: selenium/standalone-chrome:latest
    links:
      - nginx:nginx.local
  sut:
    build: .
    command: ./run_test.sh
    tty: true
    links:
      - selenium:selenium.local
