version: '2'
services:
  laravel:
    build: .
    ports:
        - "80:80"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    volumes:
      - ./var/mysql:/var/lib/mysql
  selenium:
    image: selenium/standalone-chrome:latest
    links:
      - laravel:laravel.local
  sut:
    build: .
    command: ./run_test.sh
    tty: true
    links:
      - selenium:selenium.local
