ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-name nginx"
laravel:
    build: .
    volumes:
      - ./laravel:/var/www/laravel
    links:
      - selenium:selenium.local
nginx:
    image: nginx:1.11-alpine
    container_name: nginx
    ports:
        - "80:80"
    volumes:
        - ./var/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - laravel:laravel
mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    volumes:
      - ./var/mysql:/var/lib/mysql
selenium:
    image: selenium/standalone-chrome:latest
    links:
      - "ambassador:nginx.local"
