version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /tmp
    steps:
      - run: |
          set -ex
          curl -L -o /tmp/docker-17.03.0-ce.tgz https://get.docker.com/builds/Linux/x86_64/docker-17.03.0-ce.tgz
          tar -xz -C /tmp -f /tmp/docker-17.03.0-ce.tgz
          mv /tmp/docker/* /usr/bin
      - run: |
          curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - run: |
          docker version
          docker-compose version

